spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_blog_mp?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: "SELECT 'x'"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      filter:
        stat:
          db-type: h2
          log-slow-sql: true
          slow-sql-millis: 2000
  thymeleaf:
    cache: false
    mode: html
  #Spring session配置
  session:
    store-type: redis
    redis:
      flush-mode: on_save # Sessions flush mode.
      namespace: springboot-blog-mp # Namespace for keys used to store sessions.
  # redis 连接配置
  redis:
    host: 127.0.0.1
    password:
    port: 6379
  # java mail 配置
  mail:
    host: smtp.aliyun.com
    username: xxx@aliyun.com
    password: password
    properties: {
      mail.smtp.connectiontimeout: 5000,
      mail.smtp.timeout: 3000,
      mail.smtp.writetimeout: 5000,
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory,
      mail.smtp.socketFactory.port: 465,
      mail.smtp.port: 465
    }
    port: 465
  #处理静态资源
  mvc:
    static-path-pattern: /static/**
  #缓存类型
  cache:
    type: redis
  #es
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  # 开发测试自动重启
  devtools:
    restart:
      enabled: true
      exclude: static/**
    livereload:
      enabled: true

# Mybatis Plus
mybatis-plus:
  # mapper.xml文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体类扫描
  type-aliases-package: com.li.blog.beans
  global-config:
    #主键类型
    id-type: 0
    # 字段策略
    field-strategy: 2
    #驼峰转下划线
    db-column-underline: true
    # 表前缀
    table-prefix: 'tbl_'
    # 调试器 刷新mapper
    refresh-mapper: true
    #数据库大写转下划线
    capital-mode: true
    # 逻辑删除
    logic-delete-value: -1
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.li.blog.config.handler.CustomMetaObjectHandler
  configuration:
    #配置返回数据库，自动匹配无序as
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: null
    # 一级缓存：SqlSession范围
    #local-cache-scope: session


server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      pattern: common
    basedir: ./
    max-connections: 1000
    max-threads: 300
    uri-encoding: utf-8


# 错误日志输出到文件
logging:
  file: ./logs/springboot-blog-mp.log


github:
  client:
    clientId: 08be83c60b630e57b19d # your id
    clientSecret: secret # your secret
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
  resource:
    userInfoUri: https://api.github.com/user




